/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
 *
 * Generated on: 14-Apr-2019 14:30:53
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
    0.04384142368492,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
    0.04533168875881,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.3292645521797,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
    0.06194564371621,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
      0.252725167609,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.9999989698792,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.7409344930915,   0.9123178535545 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.029278490222,   0.9744699933176 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.4631995121104,   0.9709729462277 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -0.913622134214,   0.9318840390355 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.5678212932194,   0.9263395542284 
  },
  {
                   1,                 0,                 0 
  }
};
