/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
 *
 * Generated on: 23-Mar-2019 11:54:25
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 102
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 102;
const int16_T B[102] = {
      -15,    -48,    -85,    -89,    -18,    131,    295,    371,    295,
      103,    -72,   -106,     11,    155,    173,     33,   -136,   -164,
      -11,    176,    198,     10,   -209,   -226,      4,    261,    267,
      -20,   -324,   -313,     46,    408,    371,    -85,   -520,   -445,
      144,    677,    544,   -237,   -917,   -694,    400,   1335,    964,
     -740,  -2284,  -1667,   1885,   6942,  10620,  10620,   6942,   1885,
    -1667,  -2284,   -740,    964,   1335,    400,   -694,   -917,   -237,
      544,    677,    144,   -445,   -520,    -85,    371,    408,     46,
     -313,   -324,    -20,    267,    261,      4,   -226,   -209,     10,
      198,    176,    -11,   -164,   -136,     33,    173,    155,     11,
     -106,    -72,    103,    295,    371,    295,    131,    -18,    -89,
      -85,    -48,    -15
};
