/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 21-Mar-2019 20:05:02
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 33
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/*
 * Expected path to tmwtypes.h
 * C:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 33;
const int16_T B[33] = {
      -31,    -62,    -50,     39,    178,    218,      0,   -422,   -670,
     -290,    732,   1660,   1327,   -991,  -4788,  -8366,  22944,  -8366,
    -4788,   -991,   1327,   1660,    732,   -290,   -670,   -422,      0,
      218,    178,     39,    -50,    -62,    -31
};
